const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),ts=require('typescript');
const {createHarness,payloadFor}=require('./apps-script-mocks.cjs');
function harness(){const h=createHarness();const secret='server-registration-test-key-'.repeat(3);Object.assign(h.store,{ESPARTO_REGISTRATION_BRIDGE_SECRET:secret,ESPARTO_REGISTRATION_BRIDGE_ENABLED:'true',ESPARTO_REGISTRATION_BRIDGE_SUBMIT_ENABLED:'true'});const cache=new Map();h.scope.CacheService={getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v)})};h.scope.Utilities.computeHmacSha256Signature=(msg,key)=>[...crypto.createHmac('sha256',key).update(msg).digest()];h.scope.Utilities.base64EncodeWebSafe=b=>Buffer.from(b).toString('base64url');h.scope.ContentService={MimeType:{JSON:'json'},createTextOutput:text=>({text,setMimeType(){return this;}})};
 const env={NODE_ENV:'development',EVENT_PLATFORM_GOOGLE_TEST_ENABLED:'true',EVENT_PLATFORM_APPS_SCRIPT_URL:'https://script.google.com/macros/s/TEST_ONLY/exec',EVENT_PLATFORM_REGISTRATION_SECRET:secret};let calls=0;
 const bridge={};const common={Buffer,URL,AbortSignal,Uint8Array,Date,process:{env},require:n=>n==='node:crypto'?crypto:{},fetch:async(url,options)=>{calls++;assert.equal(url,env.EVENT_PLATFORM_APPS_SCRIPT_URL);const output=h.scope.doPost({postData:{contents:options.body}});return {ok:true,json:async()=>JSON.parse(output.text)};}};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/registration/bridge.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{...common,exports:bridge});
 const route={};vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/app/api/registration/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{...common,exports:route,require:n=>n==='next/server'?{NextResponse:{json:(body,options)=>({body,...options})}}:bridge});
 const request=(data,origin='http://localhost:3000')=>{const r=new Request('http://localhost:3000/api/registration',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});r.nextUrl=new URL(r.url);return r;};return {h,env,bridge,route,request,calls:()=>calls};}
test('website API → signed adapter → existing Code.gs → mock Sheets preserves save and recovery',async()=>{const x=harness();const p=payloadFor(x.h,'E08');const saved=await x.route.POST(x.request({action:'submit',payload:p}));assert.equal(saved.body.success,true);assert.equal(x.h.batches.length,1);const recovered=await x.route.POST(x.request({action:'submit',payload:p}));assert.equal(recovered.body.receipt.regId,saved.body.receipt.regId);assert.equal(x.h.batches.length,1);assert.equal(x.calls(),2);});
test('website configuration fails closed in production or for untrusted URLs/missing secrets',()=>{const x=harness();assert.ok(x.bridge.registrationBridgeConfig());x.env.NODE_ENV='production';assert.equal(x.bridge.registrationBridgeConfig(),null);x.env.NODE_ENV='development';for(const url of ['http://127.0.0.1:4100','https://evil.example/exec','https://script.google.com/macros/s/T/dev','https://script.google.com/macros/s/T/exec?leak=true','https://script.google.com:444/macros/s/T/exec']){x.env.EVENT_PLATFORM_APPS_SCRIPT_URL=url;assert.equal(x.bridge.registrationBridgeConfig(),null);}x.env.EVENT_PLATFORM_APPS_SCRIPT_URL='https://script.google.com/macros/s/T/exec';delete x.env.EVENT_PLATFORM_REGISTRATION_SECRET;assert.equal(x.bridge.registrationBridgeConfig(),null);});
test('website API denies cross-origin, unsupported events and oversize bodies before upstream calls',async()=>{const x=harness();assert.equal((await x.route.POST(x.request({action:'catalogue'},'https://evil.example'))).status,403);assert.equal((await x.route.POST(x.request({action:'submit',payload:payloadFor(x.h,'E07')}))).status,400);assert.equal((await x.route.POST(x.request({action:'catalogue',padding:'x'.repeat(3000001)}))).status,413);assert.equal(x.calls(),0);});
test('uncertain upstream responses keep original submission retryable without auto retry',async()=>{const x=harness();delete x.h.scope.ContentService;const result=await x.route.POST(x.request({action:'submit',payload:payloadFor(x.h,'E08')}));assert.equal(result.status,503);assert.equal(result.body.retryable,true);assert.equal(x.calls(),1);assert.equal(x.h.batches.length,1);});
