'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
type Member={name:string;email:string;phone:string;rollNo:string;branch:string;year:string};
type BackendEvent={id:string;slug:string;minTeam:number;maxTeam:number;hitamFee:number;otherFee:number;feeModel:string};
type Receipt={regId:string;eventTitle:string;leadName:string;amount:number;status:string;replayed?:boolean};
const emptyMember=():Member=>({name:'',email:'',phone:'',rollNo:'',branch:'',year:''});
const branches=['CSE','CSM','CSD','ECE','EEE','MECH','ITP - CSE','ITP - MECH','IIBMP'];
const field='w-full rounded-lg border border-white/20 bg-[#120b25] p-3 text-white min-h-12 scroll-mt-28';
async function api(action:string,payload?:unknown){const response=await fetch('/api/registration-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});return response.json();}
export default function RegistrationPilot({title,backendSlug}:{title:string;backendSlug:string}) {
 const [event,setEvent]=useState<BackendEvent>();const [institution,setInstitution]=useState('HITAM');const [college,setCollege]=useState('');const [team,setTeam]=useState('');const [members,setMembers]=useState<Member[]>([emptyMember(),emptyMember()]);
 const [utr,setUtr]=useState('');const [proof,setProof]=useState('');const [agreement,setAgreement]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState<Receipt>();const [step,setStep]=useState(1);const [locked,setLocked]=useState(false);
 const requestId=useRef('');const submitted=useRef<unknown>(undefined);const inFlight=useRef(false);
 async function load(){setError('');try{const data=await api('catalogue');const found=data.events?.find((item:BackendEvent)=>item.slug===backendSlug);if(!found)throw Error(data.message||'Event unavailable');setEvent(found);}catch{setError('Start the isolated local backend to load this form.');}}
 useEffect(()=>{requestId.current=crypto.randomUUID().replaceAll('-','');void load();},[backendSlug]); // eslint-disable-line react-hooks/exhaustive-deps
 const amount=event ? (institution==='HITAM'?event.hitamFee:event.otherFee)*(event.feeModel==='person'?members.length:1):0;
 function change(index:number,key:keyof Member,value:string){setMembers(current=>current.map((member,i)=>i===index?{...member,[key]:value}:member));}
 async function upload(file:File|undefined){setProof('');if(!file)return;if(file.size>2*1024*1024 || !['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPG or WebP screenshot under 2 MB.');return;}const reader=new FileReader();reader.onload=()=>{setProof(String(reader.result));setError('');};reader.readAsDataURL(file);}
 async function submit(){if(inFlight.current||!event)return;inFlight.current=true;setBusy(true);setError('');setLocked(true);
  submitted.current ||= {requestId:requestId.current,eventId:event.id,eventSlug:event.slug,institution,college,teamSize:members.length,teamName:team,lead:members[0],members:members.slice(1),totalFee:amount,utrNumber:utr,agreement,screenshotBase64:proof,customDetails:'LOCAL TEST - isolated backend',eventAnswers:null};
  try{const result=await api('submit',submitted.current);if(result.success)setReceipt(result.receipt);else{setError(result.message||'Submission failed.');if(!result.retryable && result.code!=='RECONCILIATION_REQUIRED'){submitted.current=undefined;setLocked(false);}}}catch{setError('Connection interrupted. Retry the same submission to recover it.');}finally{inFlight.current=false;setBusy(false);}
 }
 if(receipt)return <main id="main-content" className="max-w-2xl mx-auto p-6 py-12"><p className="text-brand-orange font-bold">LOCAL TEST RECEIPT — not valid for entry</p><h1 className="text-3xl font-bold my-6">Registration submitted</h1><div className="p-6 rounded-xl border border-white/20 space-y-3"><p>{receipt.eventTitle}</p><p className="font-mono break-all">{receipt.regId}</p><p>{receipt.leadName} · ₹{receipt.amount}</p><p>Payment status: {receipt.status}</p>{receipt.replayed && <p>Existing submission recovered; no duplicate registration.</p>}</div><p className="mt-6">In the live workflow, after payment verification you receive an email from elysian@hitam.org with your ticket, QR and WhatsApp link. This local test sends no emails and takes no payment.</p><button className={field+' mt-5'} onClick={submit} disabled={busy}>Test recovery of same submission</button><Link className="block mt-6 text-brand-orange" href={`/events/${backendSlug}`}>Back to event</Link></main>;
 return <main id="main-content" className="max-w-3xl mx-auto px-5 py-12"><Link className="text-brand-orange" href={`/events/${backendSlug}`}>← Event details</Link><div className="my-6 p-4 border border-amber-400 rounded-xl text-amber-200">LOCAL TEST ONLY. Do not make a payment. All data stays in an isolated test backend; no real ticket or email is issued.</div><h1 className="text-3xl font-bold mb-5">{title}</h1>{error && <p role="alert" className="p-4 my-4 bg-red-950 rounded-xl">{error}</p>}
 {!event?<button className={field} onClick={load}>Retry loading local form</button>:<form onSubmit={e=>{e.preventDefault();if(step===1)setStep(2);else void submit();}} className="space-y-6">
 <p>Step {step} of 2 · {step===1?'Team and member details':'Payment reference and review'}</p>
 {step===1?<><label className="block">Institution<select className={field} value={institution} onChange={e=>setInstitution(e.target.value)}><option>HITAM</option><option value="Other">Other college</option></select></label>{institution==='Other'&&<label className="block">College<input className={field} value={college} onChange={e=>setCollege(e.target.value)} required maxLength={160}/></label>}
 <label className="block">Team name<input className={field} value={team} onChange={e=>setTeam(e.target.value)} required maxLength={120}/></label><p>Participants: {event.minTeam}–{event.maxTeam} (including lead)</p>
 {members.map((member,index)=><fieldset key={index} className="border border-white/20 rounded-xl p-4"><legend className="px-2">{index===0?'Team lead':'Member '+(index+1)}</legend><div className="grid sm:grid-cols-2 gap-4">{(['name','email','phone','rollNo'] as const).map(key=><label key={key}>{({name:'Name',email:'Email',phone:'WhatsApp number',rollNo:'Roll number'})[key]}<input className={field} value={member[key]} onChange={e=>change(index,key,e.target.value)} type={key==='email'?'email':key==='phone'?'tel':'text'} required={key==='name'||index===0||(key==='rollNo'&&institution==='HITAM')} maxLength={key==='email'?254:120}/></label>)}<label>Branch{institution==='HITAM'?<select aria-label="Branch" className={field} value={member.branch} onChange={e=>change(index,'branch',e.target.value)} required={index===0}><option value="">Choose branch</option>{branches.map(branch=><option key={branch}>{branch}</option>)}</select>:<input className={field} value={member.branch} onChange={e=>change(index,'branch',e.target.value)} required={index===0}/>}</label><label>Year<select aria-label="Year" className={field} value={member.year} onChange={e=>change(index,'year',e.target.value)} required={index===0}><option value="">Choose year</option>{[1,2,3,4].map(year=><option key={year} value={year}>{year}</option>)}</select></label></div></fieldset>)}
 </>:<><p className="text-xl">{team} · {members.length} participants · ₹{amount} (backend catalogue)</p><p>Use a synthetic 8–16 digit transaction reference and a test screenshot. No live payment is required.</p><fieldset disabled={locked} className="space-y-4"><label className="block">UPI transaction reference<input className={field} value={utr} onChange={e=>setUtr(e.target.value)} required pattern="[0-9]{8,16}" inputMode="numeric"/></label><label className="block">Test payment screenshot<input className={field} type="file" accept="image/png,image/jpeg,image/webp" required onChange={e=>void upload(e.target.files?.[0])}/></label><label className="flex items-start gap-3 min-h-12"><input className="mt-1 h-5 w-5 shrink-0 scroll-mt-28" type="checkbox" checked={agreement} onChange={e=>setAgreement(e.target.checked)} required/>I confirm these local test details are correct.</label></fieldset>{!locked&&<button type="button" className={field} onClick={()=>setStep(1)}>Back to details</button>}</>}
 <button disabled={busy||(step===2&&!proof)} className="rounded-xl bg-brand-orange text-white font-bold p-4 w-full" type="submit">{busy?'Submitting…':step===1?'Continue to review':locked?'Retry same submission':'Submit local test registration'}</button>
 </form>}</main>;
}
