'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import type { FestEventItem } from '@/data/events';
import { BrandHeader } from '@/components/registration/BrandHeader';
import SubmissionTicket from '@/components/registration/SubmissionTicket';
import { CalendarDays, MapPin, Users, ShieldCheck, ArrowRight } from 'lucide-react';
type Member={name:string;email:string;phone:string;rollNo:string;branch:string;year:string};
type BackendEvent={id:string;slug:string;minTeam:number;maxTeam:number;hitamFee:number;otherFee:number;feeModel:string};
type Receipt={regId:string;eventTitle:string;leadName:string;amount:number;status:string;replayed?:boolean};
const emptyMember=():Member=>({name:'',email:'',phone:'',rollNo:'',branch:'',year:''});
const branches=['CSE','CSM','CSD','ECE','EEE','MECH','ITP - CSE','ITP - MECH','IIBMP'];
const field='w-full rounded-lg border border-white/20 bg-[#120b25] p-3 text-white min-h-12 scroll-mt-28';
async function api(action:string,payload?:unknown){const response=await fetch('/api/registration-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})});return response.json();}
export default function RegistrationPilot({displayEvent}:{displayEvent:FestEventItem}) {
 const title=displayEvent.title, backendSlug=displayEvent.slug;
 const [event,setEvent]=useState<BackendEvent>();const [institution,setInstitution]=useState('HITAM');const [college,setCollege]=useState('');const [team,setTeam]=useState('');const [members,setMembers]=useState<Member[]>([emptyMember(),emptyMember()]);
 const [utr,setUtr]=useState('');const [proof,setProof]=useState('');const [agreement,setAgreement]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState<Receipt>();const [step,setStep]=useState(1);const [locked,setLocked]=useState(false);
 const requestId=useRef('');const submitted=useRef<unknown>(undefined);const inFlight=useRef(false);
 async function load(){setError('');try{const data=await api('catalogue');const found=data.events?.find((item:BackendEvent)=>item.slug===backendSlug);if(!found)throw Error(data.message||'Event unavailable');setEvent(found);}catch{setError('Start the isolated local backend to load this form.');}}
 useEffect(()=>{requestId.current=crypto.randomUUID().replaceAll('-','');void load();},[backendSlug]); // eslint-disable-line react-hooks/exhaustive-deps
 const amount=event ? (institution==='HITAM'?event.hitamFee:event.otherFee)*(event.feeModel==='person'?members.length:1):0;
 function sampleProof(){const canvas=document.createElement('canvas');canvas.width=640;canvas.height=360;const context=canvas.getContext('2d');if(!context)return;context.fillStyle='#0c0720';context.fillRect(0,0,640,360);context.fillStyle='#fbbf24';context.font='bold 28px Arial';context.fillText('LOCAL TEST PAYMENT PROOF',30,65);context.fillStyle='#ffffff';context.font='24px Arial';context.fillText('NO PAYMENT WAS MADE',30,125);context.fillText(title,30,190);context.fillText('Test amount: INR '+amount,30,240);const reference=utr||String(Date.now());context.fillText('Synthetic UTR: '+reference,30,290);setUtr(reference);setProof(canvas.toDataURL('image/png'));setError('');}
 function change(index:number,key:keyof Member,value:string){setMembers(current=>current.map((member,i)=>i===index?{...member,[key]:value}:member));}
 async function upload(file:File|undefined){setProof('');if(!file)return;if(file.size>2*1024*1024 || !['image/png','image/jpeg','image/webp'].includes(file.type)){setError('Choose a PNG, JPG or WebP screenshot under 2 MB.');return;}const reader=new FileReader();reader.onload=()=>{setProof(String(reader.result));setError('');};reader.readAsDataURL(file);}
 async function submit(){if(inFlight.current||!event)return;inFlight.current=true;setBusy(true);setError('');setLocked(true);
  submitted.current ||= {requestId:requestId.current,eventId:event.id,eventSlug:event.slug,institution,college,teamSize:members.length,teamName:team,lead:members[0],members:members.slice(1),totalFee:amount,utrNumber:utr,agreement,screenshotBase64:proof,customDetails:'LOCAL TEST - isolated backend',eventAnswers:null};
  try{const result=await api('submit',submitted.current);if(result.success)setReceipt(result.receipt);else{setError(result.message||'Submission failed.');if(!result.retryable && result.code!=='RECONCILIATION_REQUIRED'){submitted.current=undefined;setLocked(false);}}}catch{setError('Connection interrupted. Retry the same submission to recover it.');}finally{inFlight.current=false;setBusy(false);}
 }
 if(receipt)return <SubmissionTicket receipt={receipt} event={displayEvent} teamName={team} institution={institution==='HITAM'?'HITAM':college} members={members} utr={utr} onRecover={()=>void submit()} busy={busy}/>;
 return <main id="main-content" className="max-w-4xl mx-auto px-5 py-10 sm:py-14"><Link className="text-brand-orange" href={`/events/${backendSlug}`}>← Event details</Link><div className="my-5 px-4 py-3 border border-amber-400/25 bg-amber-400/5 rounded-xl text-amber-200 text-sm">LOCAL TEST ONLY. Do not make a payment. All data stays in an isolated test backend; no real ticket or email is issued.</div><header className="rounded-3xl overflow-hidden border border-white/15 bg-[#0c0720] mb-8">
 <div className="p-5 sm:p-7"><BrandHeader/></div>
 {displayEvent.bannerImage&&<Image src={displayEvent.bannerImage} alt={`${title} official event poster`} width={1600} height={600} className="w-full h-auto" priority/>}
 <div className="p-5 sm:p-7"><p className="text-brand-orange text-xs uppercase tracking-widest mb-3">{displayEvent.club} · Official registration preview</p><h1 className="text-3xl sm:text-4xl font-display font-bold mb-3">{title}</h1><p className="text-text-secondary leading-relaxed">{displayEvent.description}</p>
 <div className="grid sm:grid-cols-3 gap-4 mt-6 text-sm"><p className="flex gap-2"><CalendarDays className="w-5 h-5 text-brand-orange shrink-0"/><span>{displayEvent.date}<br/>{displayEvent.timings}</span></p><p className="flex gap-2"><MapPin className="w-5 h-5 text-brand-orange shrink-0"/>{displayEvent.venue}</p><p className="flex gap-2"><Users className="w-5 h-5 text-brand-orange shrink-0"/>{displayEvent.teamSize}</p></div>
 <div className="flex flex-wrap gap-4 items-center mt-6 pt-5 border-t border-white/10"><span className="text-text-muted text-sm">Prize pool <strong className="text-white">{displayEvent.prizePool}</strong></span>{displayEvent.brochureUrl&&<a href={displayEvent.brochureUrl} className="text-brand-orange text-sm">Read event brochure →</a>}</div>
 </div></header>{error && <p role="alert" className="p-4 my-4 bg-red-950 rounded-xl">{error}</p>}
 {!event?<button className={field} onClick={load}>Retry loading local form</button>:<form onSubmit={e=>{e.preventDefault();if(step===1)setStep(2);else void submit();}} className="space-y-6 rounded-3xl border border-white/15 bg-[#0c0720] p-5 sm:p-8">
 <ol aria-label="Registration progress" className="grid grid-cols-3 gap-2 mb-7">{['Participant details','Payment & review','Submission e-ticket'].map((label,index)=><li key={label} aria-current={step===index+1?'step':undefined} className={`rounded-xl border px-3 py-4 text-xs sm:text-sm ${step===index+1?'border-brand-orange/60 bg-brand-orange/10 text-white':'border-white/10 text-text-muted'}`}><span className="font-mono font-bold mr-2">0{index+1}</span>{label}</li>)}</ol>
 {step===1?<><label className="block">Institution<select className={field} value={institution} onChange={e=>setInstitution(e.target.value)}><option>HITAM</option><option value="Other">Other college</option></select></label>{institution==='Other'&&<label className="block">College<input className={field} value={college} onChange={e=>setCollege(e.target.value)} required maxLength={160}/></label>}
 <label className="block">Team name<input className={field} value={team} onChange={e=>setTeam(e.target.value)} required maxLength={120}/></label><p>Participants: {event.minTeam}–{event.maxTeam} (including lead) · Total ₹{amount} per team</p>
 {members.map((member,index)=><fieldset key={index} className="border border-white/15 bg-white/[0.025] rounded-2xl p-5 sm:p-6"><legend className="px-2">{index===0?'Team lead':'Member '+(index+1)}</legend><div className="grid sm:grid-cols-2 gap-4">{(['name','email','phone','rollNo'] as const).map(key=><label key={key}>{({name:'Name',email:'Email',phone:'WhatsApp number',rollNo:'Roll number'})[key]}<input className={field} value={member[key]} onChange={e=>change(index,key,e.target.value)} type={key==='email'?'email':key==='phone'?'tel':'text'} required={key==='name'||index===0||(key==='rollNo'&&institution==='HITAM')} maxLength={key==='email'?254:120}/></label>)}<label>Branch{institution==='HITAM'?<select aria-label="Branch" className={field} value={member.branch} onChange={e=>change(index,'branch',e.target.value)} required={index===0}><option value="">Choose branch</option>{branches.map(branch=><option key={branch}>{branch}</option>)}</select>:<input className={field} value={member.branch} onChange={e=>change(index,'branch',e.target.value)} required={index===0}/>}</label><label>Year<select aria-label="Year" className={field} value={member.year} onChange={e=>change(index,'year',e.target.value)} required={index===0}><option value="">Choose year</option>{[1,2,3,4].map(year=><option key={year} value={year}>{year}</option>)}</select></label></div></fieldset>)}
 </>:<><div className="rounded-2xl bg-brand-violet/10 border border-brand-violet/20 p-5"><p className="text-xs uppercase tracking-widest text-text-muted">Review your registration</p><h2 className="text-2xl font-bold mt-2">{team}</h2><p className="text-text-secondary mt-2">{members.length} participants · {institution==='HITAM'?'HITAM':college}</p><p className="text-3xl font-bold mt-4">₹{amount}<span className="text-sm font-normal text-text-muted ml-2">total · backend catalogue</span></p><div className="mt-5 pt-4 border-t border-white/10 space-y-4">{members.map((member,index)=><div key={index}><p className="font-semibold">{index===0?'Team lead':'Member '+(index+1)}: {member.name}</p><p className="text-sm text-text-secondary break-all">{member.email} · {member.rollNo}</p><p className="text-sm text-text-muted">{member.branch} · Year {member.year}</p></div>)}</div></div><p className="text-text-secondary">Use a synthetic 8–16 digit transaction reference and a test screenshot. No live payment is required.</p><button type="button" disabled={locked} onClick={sampleProof} className="rounded-xl border border-brand-orange/40 px-4 py-3 text-brand-orange">Use sample local test proof</button><fieldset disabled={locked} className="space-y-4"><label className="block">UPI transaction reference (UTR)<input className={field} value={utr} onChange={e=>setUtr(e.target.value)} required pattern="[0-9]{8,16}" inputMode="numeric"/></label><label className="block">Test payment screenshot<input className={field} type="file" accept="image/png,image/jpeg,image/webp" required={!proof} onChange={e=>void upload(e.target.files?.[0])}/></label><label className="flex items-start gap-3 min-h-12"><input className="mt-1 h-5 w-5 shrink-0 scroll-mt-28" type="checkbox" checked={agreement} onChange={e=>setAgreement(e.target.checked)} required/>I confirm these local test details are correct.</label>{proof&&<div className="rounded-xl border border-white/10 p-4"><p className="text-sm text-text-muted mb-3">Selected test payment proof</p><Image src={proof} alt="Selected local test payment screenshot" width={360} height={360} className="max-h-48 w-auto object-contain rounded-lg" unoptimized/></div>}</fieldset><p className="flex gap-2 text-sm text-text-muted"><ShieldCheck className="w-5 h-5 shrink-0 text-emerald-400"/>Payment can be verified only by organizers. This submission does not mark your payment as confirmed.</p>{!locked&&<button type="button" className={field} onClick={()=>setStep(1)}>Back to details</button>}</>}
 <button disabled={busy||(step===2&&!proof)} className="rounded-xl bg-brand-orange text-white font-bold p-4 w-full" type="submit">{busy?'Submitting…':step===1?'Continue to review':locked?'Retry same submission':'Submit local test registration'}<ArrowRight className="inline w-4 h-4 ml-2"/></button>
 </form>}</main>;
}
